# Step 3 - Create application deployment

# Now that we have a cluster running, we need to deploy our Kimai application to it.

# Tangle the code blocks below to create the deployment yaml file and the shell script that will apply the deployment.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai-gcp
  labels:
    app: kimai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimai
  template:
    metadata:
      labels:
        app: kimai
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: MYSQL_DATABASE
              value: kimai
            - name: MYSQL_USER
              value: kimai
            - name: MYSQL_PASSWORD
              value: kimai
            - name: MYSQL_ROOT_PASSWORD
              value: kimai
