---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai-app
  labels:
    app: kimai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimai-app
  template:
    metadata:
      labels:
        app: kimai-app
    spec:
     containers:
        - name: kimai
          image: kimai/kimai2
          ports:
            - containerPort: 8001
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              value: mysql://kimai:kimai@mysql:3306/kimai
