# Step 3 - Create application deployment

# Now that we have a cluster running, we need to deploy our Kimai application to it.

# Tangle the code blocks below to create the deployment yaml file and the shell script that will apply the deployment.


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai-db
  labels:
    app: kimai-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimai-db
  template:
    metadata:
      labels:
        app: kimai-db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          env:
            - name: MYSQL_DATABASE
              value: kimai
            - name: MYSQL_USER
              value: kimai
            - name: MYSQL_PASSWORD
              value: kimai
            - name: MYSQL_ROOT_PASSWORD
              value: kimai
