

# The final file creates the kubernetes loadbalancer service that we will use to access our application externally over the internet.


---
apiVersion: v1
kind: Service
metadata:
  name: kimai-app
  labels:
    app: kimai-app
spec:
  selector:
    app: kimai-app
  ports:
    - name: "kimai"
      protocol: "TCP"
      port: 8001
      targetPort: 8001
  type: LoadBalancer
